name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Test
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BS_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BS_ACCESS_KEY }}
        run: npm run test:local

      - name: Upload Logs on Failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: logs
