name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install Dependencies
        run: npm install

      - name: Install missing package
        run: npm install run@1.5.0

      - name: Test
        run: npx run browserstack

      - name: Upload Logs on Failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: logs
          path: logs
